services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DigitalMarketingFramework\Typo3\Notification\Mail\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  DigitalMarketingFramework\Typo3\Notification\Mail\Registry\EventListener\CoreRegistryUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Registry\Event\CoreRegistryUpdateEvent
